import { createSlice } from "@reduxjs/toolkit";

export const counterSlice = createSlice({
    name: "counter",
    initialState: {
        value: 0
    },
    reducers: {
        increment: (state) => {
            state.value += 1;
        },
        decrement: (state) => {
            state.value -= 1;
        }
    }
});

// export the actions generated by createSlice
export const { increment, decrement } = counterSlice.actions;

// export the selector to access the state
export const selectCount = (state) => state.counter.value;

// export the reducer to be used in the store
export default counterSlice.reducer;